import NoteList, { Note } from "@/components/noteList/NoteList";
import Head from "next/head";
import React from "react";
import { getSession } from "next-auth/react";
import Nav from "@/components/Nav/Nav";
import { GetServerSideProps } from "next/types";
import { Session } from "next-auth";

interface Props {
  session: Session | null;
  notes: Note[];
}

export default function Home({ session, notes }: Props) {
  return (
    <>
      <Head>
        <title>DigiNotes | Amazing notes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white dark:bg-black min-h-screen">
        <NoteList notes={notes} />
        <Nav />
      </main>
    </>
  );
}
