import NoteList, { Note } from "@/components/noteList/NoteList";
import Head from "next/head";
import React from "react";
import { getSession } from "next-auth/react";
import Nav from "@/components/Nav/Nav";
import { GetServerSideProps } from "next/types";
import { Session } from "next-auth";

interface Props {
  session: Session | null;
  notes: Note[];
}

export default function Home({ session, notes }: Props) {
  return (
    <>
      <Head>
        <title>Squink | Notes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white dark:bg-black min-h-screen">
        <NoteList notes={notes} />
        <Nav />
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/signin",
        permanent: false,
      },
    };
  }

  const notes = [
    {
      uuid: "1",
      title: "Nota 1",
      content: "Contenido de la nota 1",
      color: "pink",
    },
    {
      uuid: "2",
      title: "Nota 2",
      content:
        "Contenido de la nota 2 Contenido de la nota 2 Contenido de la nota 2 Contenido de la nota 2",
      color: "darkBlue",
    },
    {
      uuid: "3",
      title: "Nota 3",
      content:
        "Contenido de la nota 3 Contenido de la nota 3 Contenido de la nota 3 Contenido de la nota 3 Contenido de la nota 3 Contenido de la nota 3 Contenido de la nota 3 Contenido de la nota 3 Contenido de la nota 3 Contenido de la nota 3 Contenido de la nota 3 Contenido de la nota 3 ",
      color: "lightBlue",
    },
    {
      uuid: "4",
      title: "Nota 4",
      content: "Contenido de la nota 4",
      color: "orange",
    },
  ];

  return {
    props: {
      session,
      notes,
    },
  };
};
