import { UserContext } from "@/context/UserContext";
import { routes } from "@/utils/constants/routes";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect } from "react";

export default function Home() {
  const { authorization } = React.useContext(UserContext);
  const router = useRouter();

  useEffect(() => {
    if (!Boolean(authorization.token)) {
      router.push(routes.SIGNIN);
    }
  }, [authorization.token, router]);

  return (
    <>
      <Head>
        <title>Squink | Notes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-notes-purple dark:bg-notes-pink">
        <div>Las notas</div>
      </main>
    </>
  );
}
